on:
  workflow_dispatch:
name: Auto-Build
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: docker build -t builder .
      - run: git clone --depth=1 --branch mosh-1.3.2 https://github.com/mobile-shell/mosh.git
      - run: docker run -v $PWD/mosh:/mosh -w /mosh --name=builder builder sh -c './autogen.sh && LDFLAGS=-static ./configure && make'
      - run: ldd mosh/src/frontend/mosh-client || true
      - run: ldd mosh/src/frontend/mosh-server || true
      - run: sha256sum mosh-server mosh-client
        working-directory: mosh/src/frontend
      - uses: actions/upload-artifact@v2
        with:
          name: mosh-server
          path: mosh/src/frontend/mosh-server
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        with:
          name: mosh-client
          path: mosh/src/frontend/mosh-client
          if-no-files-found: error
